name: kafka-with-kafka-ui
services:
  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.5.2
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092,PLAINTEXT_HOST://host.docker.internal:29092
      - KAFKA_JMX_PORT=9101
      - KAFKA_JMX_HOSTNAME=localhost
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_LISTENERS=PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://kafka:29092
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - CLUSTER_ID=ZMQMqBT_SCGfB8dxNFPwzQ
    ports:
      - 9101:9101
      - 29092:29092
      - 9092:9092
      - 9093:9093
    healthcheck:
      test: kafka-cluster cluster-id --bootstrap-server kafka:9092 || exit 1
      interval: 1s
      timeout: 60s
      retries: 60

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 18080:8080
    environment:
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=host.docker.internal:29092